"""empty message

Revision ID: 8ec044325623
Revises: None
Create Date: 2016-10-20 22:21:24.992623

"""

# revision identifiers, used by Alembic.
revision = '8ec044325623'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cambio', sa.Column('exiftimestamp', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cambio', 'exiftimestamp')
    ### end Alembic commands ###
